name: "Tencent Cloud CDN Push Urls Cache"
description: "Push urls for Tencent Cloud CDN via its Python SDK API"
author: keithnull
runs:
  using: docker
  image: Dockerfile
branding:
  color: green
  icon: zap
